# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Avi Arenfeld
email: aviarenfeld@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Jekyll is super sweet! You can build static sites really fucking fast. 
  If you look under the hood you will see Ruby doing the heavy lifitng.
  Static sites are cool. As a reminder to myself "You can edit this line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description."
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: aviarenfeld
github_username:  aviarenfeld

# Build settings
markdown: kramdown
